
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

#Create the following services within the same network 

volumes:
  pgdata:
  walletstore:

networks:
  test:


services:

  explorerdb.lauranetwork.com:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    container_name: explorerdb.lauranetwork.com
    hostname: explorerdb.lauranetwork.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      - test

  explorer.lauranetwork.com:
  ##This is the service that is responsible for pulling the data from the blockchain network
    image: ghcr.io/hyperledger-labs/explorer:2.0.0
    container_name: explorer.lauranetwork.com
    hostname: explorer.mynetwork.com
    environment:
      - DATABASE_HOST=explorerdb.lauranetwork.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true 
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=${PORT:-8080}
    volumes:

    #I have to edit the config.json 
      - ./configuration.json:/opt/explorer/app/platform/fabric/config.json

    #Connection profile folder   
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile

    #Adding the public and private key data of the orgs   
      - ../artifacts/channel/crypto-config/:/etc/data
    ports:
      - 8081:8080
    depends_on:
      explorerdb.lauranetwork.com:
        condition: service_healthy
    networks:
      - test